name: positive_components
description: Positive Development Kit
version: 0.0.1
homepage: https://github.com/sgKot/positive-components

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  rxdart: ^0.23.1
